//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdeaClassificationServiceReference.IdeaClassificationSoap")]
    public interface IdeaClassificationSoap {
        
        // CODEGEN: Generating message contract since element name blurb from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse GetCategory(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse> GetCategoryAsync(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategory", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequestBody Body;
        
        public GetCategoryRequest() {
        }
        
        public GetCategoryRequest(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string blurb;
        
        public GetCategoryRequestBody() {
        }
        
        public GetCategoryRequestBody(string blurb) {
            this.blurb = blurb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponseBody Body;
        
        public GetCategoryResponse() {
        }
        
        public GetCategoryResponse(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCategoryResult;
        
        public GetCategoryResponseBody() {
        }
        
        public GetCategoryResponseBody(string GetCategoryResult) {
            this.GetCategoryResult = GetCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdeaClassificationSoapChannel : IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdeaClassificationSoapClient : System.ServiceModel.ClientBase<IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap>, IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap {
        
        public IdeaClassificationSoapClient() {
        }
        
        public IdeaClassificationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdeaClassificationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdeaClassificationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdeaClassificationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap.GetCategory(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest request) {
            return base.Channel.GetCategory(request);
        }
        
        public string GetCategory(string blurb) {
            IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest inValue = new IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest();
            inValue.Body = new IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequestBody();
            inValue.Body.blurb = blurb;
            IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse retVal = ((IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap)(this)).GetCategory(inValue);
            return retVal.Body.GetCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse> IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap.GetCategoryAsync(IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest request) {
            return base.Channel.GetCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryResponse> GetCategoryAsync(string blurb) {
            IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest inValue = new IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequest();
            inValue.Body = new IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.GetCategoryRequestBody();
            inValue.Body.blurb = blurb;
            return ((IdeaSharingPlatform.WebApi.IdeaClassificationServiceReference.IdeaClassificationSoap)(this)).GetCategoryAsync(inValue);
        }
    }
}
